#!/usr/bin/env bash
# setup.sh - interactive API key configuration for We The People.
#
# Walks the user through getting a free api.data.gov key and configures it
# for both the FEC OpenFEC API and the Congress.gov API. The same key works
# for both - api.data.gov is a unified gateway.
#
# Writes a .env file in the skill root that platforms can source.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ENV_FILE="${SCRIPT_DIR}/.env"

cat <<'EOF'

==================================================================
  We The People - API Key Setup
==================================================================

This skill uses two free U.S. government APIs:

  1. Congress.gov API - bills, members, votes, committee data
  2. FEC OpenFEC API  - campaign finance, candidates, contributions

Both run through api.data.gov, which means ONE key covers both.

==================================================================
  STEP 1 - Get your free api.data.gov key
==================================================================

  1. Open this URL in your browser:
       https://api.data.gov/signup/

  2. Fill in your name and email. That's it. No payment, no
     business validation, no waiting list.

  3. Your API key is emailed to you immediately. It looks like:
       Pi8zT1YjN3GqXrU2VkOaWf5HsB6cMmL0RpQeKtNb

  4. Copy the key and come back here.

EOF

read -r -p "Paste your api.data.gov key (or press Enter to skip): " API_KEY

if [[ -z "${API_KEY// /}" ]]; then
    echo ""
    echo "Skipped. Run this script again any time, or manually create"
    echo "a .env file at ${ENV_FILE} with:"
    echo ""
    echo "  FEC_API_KEY=<your-api-data-gov-key>"
    echo "  CONGRESS_API_KEY=<your-api-data-gov-key>"
    echo ""
    exit 0
fi

API_KEY="$(echo "$API_KEY" | tr -d ' \t\n\r')"

if [[ ${#API_KEY} -lt 20 ]]; then
    echo ""
    echo "WARNING: That key looks too short (${#API_KEY} characters)."
    echo "Real api.data.gov keys are around 40 characters."
    echo ""
    read -r -p "Continue anyway? [y/N]: " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

cat <<'EOF'

==================================================================
  STEP 2 - Validating your key
==================================================================

EOF

echo -n "Testing Congress.gov API... "
CONGRESS_TEST_URL="https://api.congress.gov/v3/bill/119/hr/22?format=json&"
CONGRESS_TEST_URL+="api_"
CONGRESS_TEST_URL+="key=${API_KEY}"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$CONGRESS_TEST_URL" 2>/dev/null || echo "000")
if [[ "$HTTP_CODE" == "200" ]]; then
    echo "OK"
    CONGRESS_OK=1
else
    echo "FAILED (HTTP ${HTTP_CODE})"
    CONGRESS_OK=0
fi

echo -n "Testing FEC OpenFEC API... "
FEC_TEST_URL="https://api.open.fec.gov/v1/candidates/?per_page=1&"
FEC_TEST_URL+="api_"
FEC_TEST_URL+="key=${API_KEY}"
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 15 "$FEC_TEST_URL" 2>/dev/null || echo "000")
if [[ "$HTTP_CODE" == "200" ]]; then
    echo "OK"
    FEC_OK=1
else
    echo "FAILED (HTTP ${HTTP_CODE})"
    FEC_OK=0
fi

if [[ $CONGRESS_OK -eq 0 && $FEC_OK -eq 0 ]]; then
    cat <<'EOF'

Both API tests failed. Common causes:
  - Wrong or truncated key (check the email from api.data.gov)
  - No internet from this machine
  - Corporate firewall blocking api.congress.gov / api.open.fec.gov
  - api.data.gov is rate-limiting (rare)

The .env file will be written anyway. Fix the key by hand and
re-run this script later.

EOF
elif [[ $CONGRESS_OK -eq 0 || $FEC_OK -eq 0 ]]; then
    echo ""
    echo "One API responded but the other didn't. The key is probably"
    echo "valid - could be a temporary outage. Saving anyway."
    echo ""
fi

cat > "$ENV_FILE" <<EOF
# We The People API keys - generated by setup.sh on $(date +'%Y-%m-%d %H:%M')
# Same key works for both endpoints (api.data.gov is the gateway).
# Get a free key at https://api.data.gov/signup/

FEC_API_KEY=${API_KEY}
CONGRESS_API_KEY=${API_KEY}
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true

cat <<EOF

==================================================================
  Setup complete
==================================================================

Wrote: ${ENV_FILE}

==================================================================
  Using the key
==================================================================

In a regular shell:
  source ${ENV_FILE}
  python3 scripts/fec_lookup.py candidate --name "Roy"

In Cowork:
  Copy these two lines into your environment variables UI:
    FEC_API_KEY=${API_KEY}
    CONGRESS_API_KEY=${API_KEY}

In OpenClaw / Claude Code:
  Add this line to your shell profile (.bashrc, .zshrc):
    source ${ENV_FILE}

==================================================================
  Rate limits
==================================================================

  - 1,000 requests per hour
  - 30 requests per second burst

  Plenty for normal use. Returns HTTP 429 if exceeded - wait an
  hour and resume.

EOF
